-   repo: git://github.com/xiachufang/pre-commit-hooks.git
    sha: 298a206604135709f011d626d1192f45dd5f08b1
    hooks:
    -   id: autopep8-wrapper
        args:
        - --in-place
        - --ignore=E501,E228,E226,E261,E262,E266,E128,E241,E402
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: pretty-format-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: flake8
        args:
        - --ignore=E501,E228,E226,E261,E262,E266,E128,E402
        - --builtins=G,request
        - --jobs=1
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
